# Generated by Django 5.0.6 on 2026-06-10 19:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('buy', 'Buy'), ('rent', 'Rent'), ('plot', 'Plot')], max_length=10)),
                ('size', models.DecimalField(decimal_places=2, help_text='Size in Marla', max_digits=8)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField()),
                ('landmark', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('owner_name', models.CharField(max_length=255)),
                ('cnic', models.CharField(help_text='Owner CNIC', max_length=15)),
                ('document_type', models.CharField(help_text='Ownership document type', max_length=100)),
                ('asking_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_negotiable', models.BooleanField(default=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('preferred_contact_time', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('agent_assigned', 'Agent Assigned'), ('visit_scheduled', 'Visit Scheduled'), ('visit_completed', 'Visit Completed'), ('under_review', 'Under Review'), ('live', 'Live'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('visit_notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('unique_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
