# Generated by Django 5.0.6 on 2026-07-22 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        ('properties', '0002_property_area_sqft_property_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingrequest',
            name='area_name',
            field=models.CharField(blank=True, default='', help_text='e.g. DHA Phase 5', max_length=100),
        ),
        migrations.AddField(
            model_name='listingrequest',
            name='area_sqft',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total area in square feet', max_digits=10),
        ),
        migrations.AddField(
            model_name='listingrequest',
            name='city',
            field=models.CharField(default='Lahore', max_length=100),
        ),
        migrations.AddField(
            model_name='listingrequest',
            name='contact_name',
            field=models.CharField(blank=True, default='', help_text='Who buyers should reach out to, if different from owner', max_length=255),
        ),
        migrations.AddField(
            model_name='listingrequest',
            name='created_property',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_listing_request', to='properties.property'),
        ),
        migrations.AddField(
            model_name='listingrequest',
            name='email',
            field=models.EmailField(default='', help_text='Used to send status updates and confirmations', max_length=254),
        ),
        migrations.AddField(
            model_name='listingrequest',
            name='floor',
            field=models.CharField(blank=True, default='', help_text='Which floor this unit is on', max_length=20),
        ),
        migrations.AddField(
            model_name='listingrequest',
            name='furnishing',
            field=models.CharField(blank=True, choices=[('unfurnished', 'Unfurnished'), ('semi_furnished', 'Semi-Furnished'), ('fully_furnished', 'Fully Furnished')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='listingrequest',
            name='has_electricity',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listingrequest',
            name='has_gas',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listingrequest',
            name='has_water',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listingrequest',
            name='property_age',
            field=models.PositiveIntegerField(blank=True, help_text='Age of the property in years', null=True),
        ),
        migrations.AlterField(
            model_name='listingrequest',
            name='document_type',
            field=models.CharField(choices=[('registry', 'Registry'), ('allotment_letter', 'Allotment Letter'), ('transfer_letter', 'Transfer Letter'), ('possession_letter', 'Possession Letter'), ('other', 'Other')], help_text='Ownership document type', max_length=100),
        ),
        migrations.AlterField(
            model_name='listingrequest',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Size in Marla (auto-derived from area_sqft)', max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='ListingRequestPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listing_photos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listings.listingrequest')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
