# Generated by Django 5.0.6 on 2026-07-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total area in square feet', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='floor',
            field=models.CharField(blank=True, default='', help_text='Which floor this unit is on', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='furnishing',
            field=models.CharField(blank=True, choices=[('unfurnished', 'Unfurnished'), ('semi_furnished', 'Semi-Furnished'), ('fully_furnished', 'Fully Furnished')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='property_age',
            field=models.PositiveIntegerField(blank=True, help_text='Age of the property in years', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='floors',
            field=models.IntegerField(blank=True, help_text='Total floors in the building', null=True),
        ),
    ]
